### ISSUE TITLE
Link to English explainer on Danmaku

### ISSUE THREAD

**Issue by svgeesus** [w3c/danmaku#2]
It would be helpful for people who are unfamiliar with Danmaku to make an informative reference to a page which explains this; preferably in English.

I found this page helpful: http://danmaku.weebly.com/ but feel free to link to a better one.

**Comment by flyingzl** [comment]
@svgeesus  thanks for the feedback. We just translate the proposal to english. you can visit [here](https://w3c-proposal-incubation.github.io/danmaku-proposal/index_en.html). Since it's still in progress, issues are very welcome 😄
