### ISSUE TITLE
What does "timeline" mean?

### ISSUE THREAD

**Issue by tidoust** [w3c/danmaku#49]
I fail to parse the definition of the [timeline](https://w3c.github.io/danmaku/usecase.html#dfn-timeline) term. Currently, it is "The on-demand barcorder is a real-time insertion or custom timeline for video playback time, live broadcasts, and other scenarios".

For instance, "barcorder" does not mean anything to me, and if it's a typo for "barcoder", I don't understand what a "barcoder" has to do with bullet chatting.

Do you mean to say that there are two types of bullet chatting comments, those that get rendered as soon as possible without any reference to the media timeline, and those that start at a specific point on the media timeline?

Also, what is the relationship/difference between this and the concepts of "appearance time" and "duration" in [Basic properties](https://w3c.github.io/danmaku/usecase.html#dfn-basic-properties)?

**Comment by xfq** [comment]
> Do you mean to say that there are two types of bullet chatting comments, those that get rendered as soon as possible without any reference to the media timeline, and those that start at a specific point on the media timeline?

I don't understand what "barcorder" means either, and I think your sentence is what the editors meant indeed.

**Comment by hax** [comment]
It seems the explanation of "timeline" have a wrong translation. The original chinese text is:

时间轴：点播弹幕为视频播放时间，直播和其他场景为实时插入或自定义时间轴。

**Comment by xfq** [comment]
After discussing with the other editors, we decided to remove this line, because it basically means the appearance time and duration of a bullet chatting comment.
