### ISSUE TITLE
Rendering determinism and ability to pause a comment

### ISSUE THREAD

**Issue by tidoust** [w3c/danmaku#50]
I'm still wondering how a possible "pause" mechanism affects rendering of a bullet chatting experience.

According to the spec, one of the [characteristics](https://w3c.github.io/danmaku/usecase.html#bullet-chatting-characteristics) of a bullet chattting experience is "Deterministic of rendering", but if an application supports a "pause" feature for an individual bullet chatting comment, wouldn't the rendering determinism be affected when a user pauses a comment?

In the spec, it may just be a matter of completing the definition, for instance:

```html
<li><dfn>Rendering determinism</dfn>: Provided that the bullet chatting
<a>container</a> and the <a>bullet chatting comment</a> are fixed, and
in the absence of user interaction (e.g. to pause a <a>bullet chatting
comment</a>), then the rendering position, order and timing of <a>bullet
chatting comment</a> are always the same.</li>
```

(I also suggest to rename the characteristic as "Rendering determinism" which sounds more English to me)

**Comment by hax** [comment]
Personally I didn't see "pause" feature for an individual bullet chatting comment on any app. What u can do is just "pause" everything (video and all bullet chatting comments on the screen).

**Comment by xfq** [comment]
> Personally I didn't see "pause" feature for an individual bullet chatting comment on any app. What u can do is just "pause" everything (video and all bullet chatting comments on the screen).

Bilibili doesn't seem to have this feature. You can try enabling bullet chatting in the following videos and hover over a bullet chatting comment to see the effect:

* https://www.mgtv.com/l/100028999/7960509.html
* https://v.youku.com/v_show/id_XNDYyODE0ODQwMA==.html
* https://www.iqiyi.com/v_19rrok4nt0.html

**Comment by hax** [comment]
I found that their Web interface support pause single comment but app (at least App on MacOS) not 😕
