### ISSUE TITLE
Independence of space and layers

### ISSUE THREAD

**Issue by tidoust** [w3c/danmaku#51]
The [Independence of space](https://w3c.github.io/danmaku/usecase.html#dfn-independence-of-space) characteristic describes a system of layers that does not seem to appear anywhere else, but that seems actually important to understand how things get rendered in practice.

Are the following assertions all true?

1. A bullet chatting experience is composed of a set of superposed layers.
2. A bullet chatting comment belongs to one and only one layer.
3. A layer only contains bullet chatting comments that have a given [mode](https://w3c.github.io/danmaku/usecase.html#dfn-mode).
4. Within a layer, bullet chatting comments never overlap (unless a user pauses a comment?)

In particular, is 4 true? I'm asking because the proposed API includes an [allowOverlap](https://w3c.github.io/danmaku/api.html#dfn-allowoverlap) attribute. Or should 4. be more "does not overlap unless there are too many comments to render and overlap is allowed"?

If 1-3 are true, I believe it would be useful to introduce the term "layer" more formally in the spec.

**Comment by xfq** [comment]
All assertions are true. I'll try submitting a PR to fix this issue.
