### ISSUE TITLE
allowOverlap attribute for comments in different modes

### ISSUE THREAD

**Issue by tiansh** [w3c/danmaku#6]
As the draft described, there are 4 modes of bulletchat element. The example only shows how to handle `scroll` mode bulletchat elements when allowOverlap is set. May a `bulletchat[mode="top"]` overlap `bulletchat[mode="scroll"]` when allowOverlap is set to true?

**Comment by MagicJuly** [comment]
Each mode can be thought of as a different virtual layer, and "allowOverlap" is to control whether the mode itself allows overlap, so whether or not "allowOverlap" is true, `bulletchat[mode="top"]` can be overlapped in `bulletchat[mode="scroll"]`.

**Comment by tiansh** [comment]
Maybe this can be clarify in the specification then. :)

**Comment by DIYgod** [comment]
@tiansh refer to [1.2 Bullet Chatting characteristics](https://w3c.github.io/danmaku/index_en.html#bullet-chatting-characteristics)
