### ISSUE TITLE
Attributes vs. Styles

### ISSUE THREAD

**Issue by tiansh** [w3c/danmaku#7]
`play-state`, `duration`, `delay` are three styles listed in current draft. Why they are styles instead of attributes?

`play-state` looks like `HTMLMediaElement.paused` to me, which would be an attribute.

It is normal that `delay` of each comments are different, and using style for it is confusing.

**Comment by MagicJuly** [comment]
@tiansh `<bulletchatlist>` and `<bulletchat>` element can be understood as adding an animation effect, and Bullet Chatting is not necessarily strongly associated with `<video>`, so at present we think that use style is better, referring to CSS animation.

**Comment by tiansh** [comment]
But this also means that `<bulletchat>` cannot work on useragents without CSS support. Did I understand correctly?

**Comment by DIYgod** [comment]
@tiansh Yes, you are right.
