### ISSUE TITLE
把弹幕变成规范这个提案的目的是什么？

### ISSUE THREAD

**Issue by xfq** [w3c/danmaku#9]
**Issue by [LongTengDao](https://github.com/LongTengDao)**
_Jul 18, 2019, 8:33 PM GMT+8_
_Originally opened as [w3c-proposal-incubation/w3c-proposal-incubation.github.io#4](https://github.com/w3c-proposal-incubation/w3c-proposal-incubation.github.io/issues/4)_

原生化，以提升性能？
还是只是某种具体实现（或许是最佳实践）的公开文档？

**Comment by xfq** [comment]
**Comment by [flyingzl](https://github.com/flyingzl)**
_Jul 24, 2019, 11:12 AM GMT+8_

为什么要有规范？其实我想更多的是为了标准化，为了减轻开发者的负担。比如现在有web，有各种小程序，web上一套弹幕实现，小程序上一种弹幕实现，是否可以考虑统一起来呢？ 

比如以前我们想播放一个视频，需要flash，现在有了html5的 video就方便了很多。为了丰富观看视频体验，亚洲地区有了弹幕，弹幕又可以用css3或者canvas来实现，能否更加简单一点，用一两个标签来实现呢？ 所以中文兴趣组就考虑能否提一个弹幕的规范， 来更加方便快捷的进行web开发。

**Comment by xfq** [comment]
**Comment by [LongTengDao](https://github.com/LongTengDao)**
_Jul 24, 2019, 3:29 PM GMT+8_

@flyingzl 原来如此！这么说可以可以基于理性和实践提issue建议和PR，而不局限于当前项目的参与者基于特定实现优化、旁人只能当看客？又或者现在还没到那么成熟的阶段，虽然意图如此，但是暂时对公众参与并不具备那样的容纳力？谢谢解答

另外你提到的中文兴趣组是什么？

**Comment by flyingzl** [comment]
@LongTengDao  是的，这个任何人都可以提交pull request，提交的自己的意见。现在现在是早期阶段，非常欢迎提交建议或者新的一些想法。 

w3c是一个标准组织，虽然中国有很多厂商也参与其中，但是由于语言沟通限制，有些想法不能很好的表达出来，所以特成立了[w3c 中文兴趣组](https://github.com/w3c/chinese-ig)，方便用中文更好的沟通和了解w3c的相关规程，同时也方便孵化一些新的标准，然后推荐给浏览器厂商来实现。w3c中文兴趣组的具体情况，你可以访问 https://github.com/w3c/chinese-ig 看看

**Comment by iwestlin** [comment]
marquee 重出江湖😱

**Comment by sivan** [comment]
`<marquee loop="1">一条弹幕</marquee>` 美滋滋。
